### ISSUE TITLE
bug in website

### ISSUE THREAD

**Issue by Jhubham567** [Shubhamnpk/Yo-guru#7]
**Describe the bug**
the alignment of the image and its size big as a holy cow improve it 
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to your website 
2. Click on it
3. Scroll down to IMG section 

**Expected behaviour**
it should be in proper alignment and size

**Screenshots**
naha I will not do that 

**Desktop (please complete the following information):**
 - OS: windows 
 - Browser chrome
 - Version idk

**Smartphone (please complete the following information):**

**Comment by Shubhamnpk** [comment]
Thank you for identifying the **bug**. I will endeavour to resolve it promptly, and I appreciate the **feedback** /**issue** report.
